// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrgg-2_8Plj4BnOF2qbETJzINqYAfjgM',
    appId: '1:739869088614:web:a8238487593096798a86a7',
    messagingSenderId: '739869088614',
    projectId: 'skill-link-e7d26',
    authDomain: 'skill-link-e7d26.firebaseapp.com',
    storageBucket: 'skill-link-e7d26.firebasestorage.app',
    measurementId: 'G-JTSKCENRCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdy5Gn655ZdkU9Co8e2eHVQnHsHdNwUU',
    appId: '1:739869088614:android:d36d0212972db8a48a86a7',
    messagingSenderId: '739869088614',
    projectId: 'skill-link-e7d26',
    storageBucket: 'skill-link-e7d26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2BVI9_GVMVwqw8D4mI9chQLw9pfyYYq0',
    appId: '1:739869088614:ios:a256f37c34f2fb028a86a7',
    messagingSenderId: '739869088614',
    projectId: 'skill-link-e7d26',
    storageBucket: 'skill-link-e7d26.firebasestorage.app',
    iosBundleId: 'com.example.skillLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2BVI9_GVMVwqw8D4mI9chQLw9pfyYYq0',
    appId: '1:739869088614:ios:a256f37c34f2fb028a86a7',
    messagingSenderId: '739869088614',
    projectId: 'skill-link-e7d26',
    storageBucket: 'skill-link-e7d26.firebasestorage.app',
    iosBundleId: 'com.example.skillLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLrgg-2_8Plj4BnOF2qbETJzINqYAfjgM',
    appId: '1:739869088614:web:53f9fabb31fd207e8a86a7',
    messagingSenderId: '739869088614',
    projectId: 'skill-link-e7d26',
    authDomain: 'skill-link-e7d26.firebaseapp.com',
    storageBucket: 'skill-link-e7d26.firebasestorage.app',
    measurementId: 'G-64RD9B83QT',
  );
}
